title: Soo.P's Data Journal
logo: logo2.png # you can add own logo.
description: Data-Driven AMAZING Decision Makerê°€ ë˜ê³  ì‹¶ì€, ìˆ²ì´ì…ë‹ˆë‹¤!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rimiiii.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Soo.P
  image: '/assets/img/small_profile2.jpg'
  job: Soo.P's Data Journal
  bio: Data-Driven AMAZING Decision Makerê°€ ë˜ê³  ì‹¶ì€, ìˆ²ì´ì…ë‹ˆë‹¤! (ìš”ì¦˜ì€ ì½”ë”© ê³µë¶€ì¤‘ğŸ‘Š)
  email: ggohee0410@gmail.com


# Contact links
contact:
  - name: Github
    link: https://github.com/Soohee410
  - name: Instagram
    link: https://instagram.com/soop0410
  - name: Linkedin
    link: https://www.linkedin.com/in/soohee-park-265901202


# Comment Section (Disqus)
disqus-identifier: soo-ps-data-story # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: 'UA-164687013-1' # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tags
#tag_page_layout:      tag-page
#tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
