title: Rimiiii's Data Log
logo: logo.png # you can add own logo.
description: ì´ê²ƒì €ê²ƒ ë„ì ì´ëŠ” ë¸”ë¡œê·¸ì…ë‹ˆë‹¤âœ¨ ì•Œê³ ë¦¬ì¦˜, ë”¥ëŸ¬ë‹, ì±… ë¦¬ë·° ë“±ë“±ë“± ë‹¤ì–‘í•œ ê²ƒë“¤ì„ ë‹¤ë¤„ë³´ë ¤ê³  í•©ë‹ˆë‹¤ğŸŒ¼
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rimiiii.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Rimiiii
  image: '/assets/img/small_profile.jpg'
  job: Rimiiii's Data Log 
  bio: ì´ê²ƒì €ê²ƒ ë„ì ì´ëŠ” ë¸”ë¡œê·¸ì…ë‹ˆë‹¤âœ¨ ì•Œê³ ë¦¬ì¦˜, ë”¥ëŸ¬ë‹, ì±… ë¦¬ë·° ë“±ë“±ë“± ë‹¤ì–‘í•œ ê²ƒë“¤ì„ ë‹¤ë¤„ë³´ë ¤ê³  í•©ë‹ˆë‹¤ğŸŒ¼
  email: rimiiii.u@gmail.com


# Contact links
contact:
  - name: Github
    link: https://github.com/rimiiii
  - name: Instagram
    link: https://instagram.com/rimiiii_u
  - name: Gmail
    link: rimiiii.u@gmail.com


# Comment Section (Disqus)
disqus-identifier: my-hexo-blog-8 # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: 'UA-215535194-1' # add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-paginate
paginate: 5
paginate_path: /page:num/

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tags
#tag_page_layout:      tag-page
#tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
